[0m17:09:51.707751 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108c6ecf0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10c663890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10c663750>]}


============================== 17:09:51.713497 | 69b63001-cfa3-4dd8-8e1e-b417c4a5933b ==============================
[0m17:09:51.713497 [info ] [MainThread]: Running with dbt=1.9.6
[0m17:09:51.713837 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/sanchitgarg/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt init heymax_analytics', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m17:09:51.721624 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'PosixPath'.. Dictionary: {'dir': PosixPath('/Users/sanchitgarg/.dbt')}
[0m17:09:51.721891 [info ] [MainThread]: Creating dbt configuration folder at 
[0m17:09:51.722645 [debug] [MainThread]: Starter project path: /Users/sanchitgarg/Desktop/heymax_project/venv/lib/python3.13/site-packages/dbt/include/starter_project
[0m17:09:51.726171 [info ] [MainThread]: 
Your new dbt project "heymax_analytics" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m17:09:51.726420 [info ] [MainThread]: Setting up your profile.
[0m17:10:59.211894 [info ] [MainThread]: Profile heymax_analytics written to /Users/sanchitgarg/.dbt/profiles.yml using target's sample configuration. Once updated, you'll be able to start developing with dbt.
[0m17:10:59.226384 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 67.55744, "process_in_blocks": "0", "process_kernel_time": 0.186088, "process_mem_max_rss": "101056512", "process_out_blocks": "0", "process_user_time": 0.902996}
[0m17:10:59.226904 [debug] [MainThread]: Command `dbt init` succeeded at 17:10:59.226784 after 67.56 seconds
[0m17:10:59.227489 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10c6e2650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10c78a8d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10c7c4af0>]}
[0m17:10:59.227806 [debug] [MainThread]: Flushing usage events
[0m17:11:00.251035 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:11:41.206903 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1079c5be0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108757b10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108757c50>]}


============================== 15:11:41.211068 | 045fb9d7-a1f6-426f-bb4b-aeb2c4830e0f ==============================
[0m15:11:41.211068 [info ] [MainThread]: Running with dbt=1.9.6
[0m15:11:41.211392 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/Users/sanchitgarg/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run --select stg_events', 'send_anonymous_usage_stats': 'True'}
[0m15:11:41.211693 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/sanchitgarg/Desktop/heymax_project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:11:41.226817 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.0599605, "process_in_blocks": "0", "process_kernel_time": 0.120719, "process_mem_max_rss": "103006208", "process_out_blocks": "0", "process_user_time": 0.638436}
[0m15:11:41.227209 [debug] [MainThread]: Command `dbt run` failed at 15:11:41.227147 after 0.06 seconds
[0m15:11:41.227426 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10862fa80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1087b0cb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108651040>]}
[0m15:11:41.227633 [debug] [MainThread]: Flushing usage events
[0m15:11:42.260216 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m19:08:42.780406 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105369be0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110007b10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110007c50>]}


============================== 19:08:42.784320 | ed17e698-921d-4443-a677-ed2aedd8dbf6 ==============================
[0m19:08:42.784320 [info ] [MainThread]: Running with dbt=1.9.6
[0m19:08:42.784635 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/sanchitgarg/.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt run --select daily_active_users', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:08:42.784909 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/sanchitgarg/Desktop/heymax_project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:08:42.786383 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.044597708, "process_in_blocks": "0", "process_kernel_time": 0.133572, "process_mem_max_rss": "102809600", "process_out_blocks": "0", "process_user_time": 0.655314}
[0m19:08:42.786644 [debug] [MainThread]: Command `dbt run` failed at 19:08:42.786592 after 0.04 seconds
[0m19:08:42.786840 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106eeba80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110064cb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106f05040>]}
[0m19:08:42.787029 [debug] [MainThread]: Flushing usage events
[0m19:08:43.981288 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m19:09:44.084692 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10856dbe0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1092fbb10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1092fbc50>]}


============================== 19:09:44.089032 | 1302a6fb-31e4-4b9d-a7b8-8d45421f8b20 ==============================
[0m19:09:44.089032 [info ] [MainThread]: Running with dbt=1.9.6
[0m19:09:44.089411 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/Users/sanchitgarg/.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run --select daily_active_users', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m19:09:44.089719 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/sanchitgarg/Desktop/heymax_project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:09:44.091624 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.04370846, "process_in_blocks": "0", "process_kernel_time": 0.124021, "process_mem_max_rss": "102776832", "process_out_blocks": "0", "process_user_time": 0.639098}
[0m19:09:44.091888 [debug] [MainThread]: Command `dbt run` failed at 19:09:44.091833 after 0.04 seconds
[0m19:09:44.092076 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1091d3a80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109358cb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1091fd040>]}
[0m19:09:44.092248 [debug] [MainThread]: Flushing usage events
[0m19:09:45.290911 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:54:13.873361 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107f39be0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108ccbb10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108ccbc50>]}


============================== 11:54:13.877051 | e3a03616-1db3-4fbc-abc2-51aff71a1c44 ==============================
[0m11:54:13.877051 [info ] [MainThread]: Running with dbt=1.9.6
[0m11:54:13.877386 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/sanchitgarg/.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m11:54:13.877679 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/sanchitgarg/Desktop/heymax_project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:54:13.879522 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.045980956, "process_in_blocks": "0", "process_kernel_time": 0.118425, "process_mem_max_rss": "102252544", "process_out_blocks": "0", "process_user_time": 0.636327}
[0m11:54:13.879787 [debug] [MainThread]: Command `dbt run` failed at 11:54:13.879737 after 0.05 seconds
[0m11:54:13.879974 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108baba80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108d18cb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108bc9040>]}
[0m11:54:13.880144 [debug] [MainThread]: Flushing usage events
[0m11:54:15.189832 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:45:40.539869 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9cf0ca35b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9cf1a635e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9ce0560550>]}


============================== 14:45:40.548813 | 808feb4a-b178-4b10-9f88-0445e9348f13 ==============================
[0m14:45:40.548813 [info ] [MainThread]: Running with dbt=1.8.7
[0m14:45:40.549413 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/sanchitgarg/.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt run', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:45:40.549989 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/sanchitgarg/Desktop/heymax_project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:45:40.559760 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.08999933, "process_user_time": 0.93212, "process_kernel_time": 0.151181, "process_mem_max_rss": "84885504", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m14:45:40.560503 [debug] [MainThread]: Command `dbt run` failed at 14:45:40.560248 after 0.09 seconds
[0m14:45:40.560884 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9cf0ca35b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9cf1ae74c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9ce0b2b2b0>]}
[0m14:45:40.561233 [debug] [MainThread]: Flushing usage events
