[0m17:09:51.707751 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108c6ecf0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10c663890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10c663750>]}


============================== 17:09:51.713497 | 69b63001-cfa3-4dd8-8e1e-b417c4a5933b ==============================
[0m17:09:51.713497 [info ] [MainThread]: Running with dbt=1.9.6
[0m17:09:51.713837 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/sanchitgarg/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt init heymax_analytics', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m17:09:51.721624 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'PosixPath'.. Dictionary: {'dir': PosixPath('/Users/sanchitgarg/.dbt')}
[0m17:09:51.721891 [info ] [MainThread]: Creating dbt configuration folder at 
[0m17:09:51.722645 [debug] [MainThread]: Starter project path: /Users/sanchitgarg/Desktop/heymax_project/venv/lib/python3.13/site-packages/dbt/include/starter_project
[0m17:09:51.726171 [info ] [MainThread]: 
Your new dbt project "heymax_analytics" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m17:09:51.726420 [info ] [MainThread]: Setting up your profile.
[0m17:10:59.211894 [info ] [MainThread]: Profile heymax_analytics written to /Users/sanchitgarg/.dbt/profiles.yml using target's sample configuration. Once updated, you'll be able to start developing with dbt.
[0m17:10:59.226384 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 67.55744, "process_in_blocks": "0", "process_kernel_time": 0.186088, "process_mem_max_rss": "101056512", "process_out_blocks": "0", "process_user_time": 0.902996}
[0m17:10:59.226904 [debug] [MainThread]: Command `dbt init` succeeded at 17:10:59.226784 after 67.56 seconds
[0m17:10:59.227489 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10c6e2650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10c78a8d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10c7c4af0>]}
[0m17:10:59.227806 [debug] [MainThread]: Flushing usage events
[0m17:11:00.251035 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:11:41.206903 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1079c5be0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108757b10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108757c50>]}


============================== 15:11:41.211068 | 045fb9d7-a1f6-426f-bb4b-aeb2c4830e0f ==============================
[0m15:11:41.211068 [info ] [MainThread]: Running with dbt=1.9.6
[0m15:11:41.211392 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/Users/sanchitgarg/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run --select stg_events', 'send_anonymous_usage_stats': 'True'}
[0m15:11:41.211693 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/sanchitgarg/Desktop/heymax_project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:11:41.226817 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.0599605, "process_in_blocks": "0", "process_kernel_time": 0.120719, "process_mem_max_rss": "103006208", "process_out_blocks": "0", "process_user_time": 0.638436}
[0m15:11:41.227209 [debug] [MainThread]: Command `dbt run` failed at 15:11:41.227147 after 0.06 seconds
[0m15:11:41.227426 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10862fa80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1087b0cb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108651040>]}
[0m15:11:41.227633 [debug] [MainThread]: Flushing usage events
[0m15:11:42.260216 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m19:08:42.780406 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105369be0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110007b10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110007c50>]}


============================== 19:08:42.784320 | ed17e698-921d-4443-a677-ed2aedd8dbf6 ==============================
[0m19:08:42.784320 [info ] [MainThread]: Running with dbt=1.9.6
[0m19:08:42.784635 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/sanchitgarg/.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt run --select daily_active_users', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:08:42.784909 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/sanchitgarg/Desktop/heymax_project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:08:42.786383 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.044597708, "process_in_blocks": "0", "process_kernel_time": 0.133572, "process_mem_max_rss": "102809600", "process_out_blocks": "0", "process_user_time": 0.655314}
[0m19:08:42.786644 [debug] [MainThread]: Command `dbt run` failed at 19:08:42.786592 after 0.04 seconds
[0m19:08:42.786840 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106eeba80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110064cb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106f05040>]}
[0m19:08:42.787029 [debug] [MainThread]: Flushing usage events
[0m19:08:43.981288 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m19:09:44.084692 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10856dbe0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1092fbb10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1092fbc50>]}


============================== 19:09:44.089032 | 1302a6fb-31e4-4b9d-a7b8-8d45421f8b20 ==============================
[0m19:09:44.089032 [info ] [MainThread]: Running with dbt=1.9.6
[0m19:09:44.089411 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/Users/sanchitgarg/.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run --select daily_active_users', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m19:09:44.089719 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/sanchitgarg/Desktop/heymax_project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:09:44.091624 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.04370846, "process_in_blocks": "0", "process_kernel_time": 0.124021, "process_mem_max_rss": "102776832", "process_out_blocks": "0", "process_user_time": 0.639098}
[0m19:09:44.091888 [debug] [MainThread]: Command `dbt run` failed at 19:09:44.091833 after 0.04 seconds
[0m19:09:44.092076 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1091d3a80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109358cb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1091fd040>]}
[0m19:09:44.092248 [debug] [MainThread]: Flushing usage events
[0m19:09:45.290911 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:54:13.873361 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107f39be0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108ccbb10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108ccbc50>]}


============================== 11:54:13.877051 | e3a03616-1db3-4fbc-abc2-51aff71a1c44 ==============================
[0m11:54:13.877051 [info ] [MainThread]: Running with dbt=1.9.6
[0m11:54:13.877386 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/sanchitgarg/.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m11:54:13.877679 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/sanchitgarg/Desktop/heymax_project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:54:13.879522 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.045980956, "process_in_blocks": "0", "process_kernel_time": 0.118425, "process_mem_max_rss": "102252544", "process_out_blocks": "0", "process_user_time": 0.636327}
[0m11:54:13.879787 [debug] [MainThread]: Command `dbt run` failed at 11:54:13.879737 after 0.05 seconds
[0m11:54:13.879974 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108baba80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108d18cb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108bc9040>]}
[0m11:54:13.880144 [debug] [MainThread]: Flushing usage events
[0m11:54:15.189832 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:45:40.539869 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9cf0ca35b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9cf1a635e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9ce0560550>]}


============================== 14:45:40.548813 | 808feb4a-b178-4b10-9f88-0445e9348f13 ==============================
[0m14:45:40.548813 [info ] [MainThread]: Running with dbt=1.8.7
[0m14:45:40.549413 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/sanchitgarg/.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt run', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:45:40.549989 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/sanchitgarg/Desktop/heymax_project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:45:40.559760 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.08999933, "process_user_time": 0.93212, "process_kernel_time": 0.151181, "process_mem_max_rss": "84885504", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m14:45:40.560503 [debug] [MainThread]: Command `dbt run` failed at 14:45:40.560248 after 0.09 seconds
[0m14:45:40.560884 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9cf0ca35b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9cf1ae74c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9ce0b2b2b0>]}
[0m14:45:40.561233 [debug] [MainThread]: Flushing usage events
[0m18:33:23.726591 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fdf29148a00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fdf2a8ab760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fdf180c05e0>]}


============================== 18:33:23.731695 | a67d914c-552f-451c-b88d-7ce6d417b022 ==============================
[0m18:33:23.731695 [info ] [MainThread]: Running with dbt=1.8.7
[0m18:33:23.732213 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/sanchitgarg/.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m18:33:23.732801 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/sanchitgarg/Desktop/heymax_project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:33:23.742723 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.10191704, "process_user_time": 0.923729, "process_kernel_time": 0.536627, "process_mem_max_rss": "84791296", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m18:33:23.743445 [debug] [MainThread]: Command `dbt run` failed at 18:33:23.743195 after 0.10 seconds
[0m18:33:23.743809 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fdf29148a00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fdf2a8ed8b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fdf180c0e80>]}
[0m18:33:23.744154 [debug] [MainThread]: Flushing usage events
[0m19:36:49.249567 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9580c78130>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9550812c40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9550832700>]}


============================== 19:36:49.255850 | 164d901b-e76d-40e2-aad4-e111b91fb57a ==============================
[0m19:36:49.255850 [info ] [MainThread]: Running with dbt=1.8.7
[0m19:36:49.256539 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/Users/sanchitgarg/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt build', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:36:49.257149 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/sanchitgarg/Desktop/heymax_project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:36:49.265241 [debug] [MainThread]: Resource report: {"command_name": "build", "command_wall_clock_time": 0.09365967, "process_user_time": 1.010774, "process_kernel_time": 0.557017, "process_mem_max_rss": "85782528", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m19:36:49.266345 [debug] [MainThread]: Command `dbt build` failed at 19:36:49.266007 after 0.10 seconds
[0m19:36:49.266865 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9580c78130>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f95507f74c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9550469e50>]}
[0m19:36:49.267390 [debug] [MainThread]: Flushing usage events
[0m23:11:23.832930 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106792390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106785390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106792450>]}


============================== 23:11:23.836066 | b437c9b1-6bbb-4193-ab97-2419a5c28c6a ==============================
[0m23:11:23.836066 [info ] [MainThread]: Running with dbt=1.8.7
[0m23:11:23.836433 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/sanchitgarg/.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m23:11:23.836772 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/sanchitgarg/Desktop/heymax_project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:11:23.842438 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.047724877, "process_user_time": 0.648521, "process_kernel_time": 0.135915, "process_mem_max_rss": "101548032", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m23:11:23.842816 [debug] [MainThread]: Command `dbt run` failed at 23:11:23.842753 after 0.05 seconds
[0m23:11:23.843126 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1067be350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10638aa90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x102460910>]}
[0m23:11:23.843367 [debug] [MainThread]: Flushing usage events
[0m23:46:43.779311 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10622e390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10625dc50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10625e3d0>]}


============================== 23:46:43.783146 | 689ad334-d1b7-4859-bc09-c2512d817e90 ==============================
[0m23:46:43.783146 [info ] [MainThread]: Running with dbt=1.8.7
[0m23:46:43.783539 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/Users/sanchitgarg/.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt build', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m23:46:43.783923 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/sanchitgarg/Desktop/heymax_project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:46:43.785773 [debug] [MainThread]: Resource report: {"command_name": "build", "command_wall_clock_time": 0.046942376, "process_user_time": 0.691312, "process_kernel_time": 0.134171, "process_mem_max_rss": "102039552", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m23:46:43.786095 [debug] [MainThread]: Command `dbt build` failed at 23:46:43.786040 after 0.05 seconds
[0m23:46:43.786338 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x102401390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1062727d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1005cc990>]}
[0m23:46:43.786550 [debug] [MainThread]: Flushing usage events
[0m12:31:57.769687 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1076d4690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1076d7dd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1076d7610>]}


============================== 12:31:57.773584 | f8f777c6-ef1a-43b6-932c-6f8628de109f ==============================
[0m12:31:57.773584 [info ] [MainThread]: Running with dbt=1.8.7
[0m12:31:57.773960 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/sanchitgarg/.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt build', 'send_anonymous_usage_stats': 'True'}
[0m12:31:57.774330 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/sanchitgarg/Desktop/heymax_project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:31:57.776091 [debug] [MainThread]: Resource report: {"command_name": "build", "command_wall_clock_time": 0.048943833, "process_user_time": 0.635035, "process_kernel_time": 0.138358, "process_mem_max_rss": "100974592", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m12:31:57.776418 [debug] [MainThread]: Command `dbt build` failed at 12:31:57.776360 after 0.05 seconds
[0m12:31:57.776655 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1072c8b90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1072c9350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10338db90>]}
[0m12:31:57.776856 [debug] [MainThread]: Flushing usage events
[0m15:41:17.141903 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109475310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10948b9d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10948bf90>]}


============================== 15:41:17.145785 | 2b578ba3-0c2a-4979-98da-a430f7a34b0f ==============================
[0m15:41:17.145785 [info ] [MainThread]: Running with dbt=1.8.7
[0m15:41:17.146143 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/Users/sanchitgarg/.dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt deps', 'send_anonymous_usage_stats': 'True'}
[0m15:41:17.146705 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/sanchitgarg/Desktop/heymax_project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:41:17.148500 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_wall_clock_time": 0.048161626, "process_user_time": 0.711289, "process_kernel_time": 0.147024, "process_mem_max_rss": "102760448", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m15:41:17.148789 [debug] [MainThread]: Command `dbt deps` failed at 15:41:17.148737 after 0.05 seconds
[0m15:41:17.149016 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1094a5750>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1050b1c10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1094763d0>]}
[0m15:41:17.149209 [debug] [MainThread]: Flushing usage events
[0m23:42:19.007369 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106750c50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106753bd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10675d150>]}


============================== 23:42:19.010902 | 4add04a8-b661-4c5f-a053-8fa7aba6b87b ==============================
[0m23:42:19.010902 [info ] [MainThread]: Running with dbt=1.8.7
[0m23:42:19.011265 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/sanchitgarg/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt build', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m23:42:19.011635 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/sanchitgarg/Desktop/heymax_project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:42:19.013163 [debug] [MainThread]: Resource report: {"command_name": "build", "command_wall_clock_time": 0.0444635, "process_user_time": 0.625463, "process_kernel_time": 0.128821, "process_mem_max_rss": "101335040", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m23:42:19.013470 [debug] [MainThread]: Command `dbt build` failed at 23:42:19.013412 after 0.04 seconds
[0m23:42:19.013726 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106735510>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10675ea90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1010c9b50>]}
[0m23:42:19.013938 [debug] [MainThread]: Flushing usage events
[0m20:15:23.471582 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1047230d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1047172d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104765b10>]}


============================== 20:15:23.474665 | 56866df3-80ea-41a2-8b3e-bb155c158dfe ==============================
[0m20:15:23.474665 [info ] [MainThread]: Running with dbt=1.8.7
[0m20:15:23.475020 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/sanchitgarg/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'invocation_command': 'dbt run', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m20:15:23.475366 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/sanchitgarg/Desktop/heymax_project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:15:23.477095 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.044238374, "process_user_time": 0.623398, "process_kernel_time": 0.129348, "process_mem_max_rss": "100990976", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m20:15:23.477380 [debug] [MainThread]: Command `dbt run` failed at 20:15:23.477332 after 0.04 seconds
[0m20:15:23.477591 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104722610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1002be190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104716dd0>]}
[0m20:15:23.477784 [debug] [MainThread]: Flushing usage events
[0m16:11:13.263789 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1068861d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1068b18d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1068b2090>]}


============================== 16:11:13.267997 | e2a66296-4d2c-4433-a8da-2bdd0284110c ==============================
[0m16:11:13.267997 [info ] [MainThread]: Running with dbt=1.8.7
[0m16:11:13.268523 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/Users/sanchitgarg/.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt build', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:11:13.269043 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/sanchitgarg/Desktop/heymax_project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:11:13.270762 [debug] [MainThread]: Resource report: {"command_name": "build", "command_wall_clock_time": 0.05480904, "process_user_time": 0.701391, "process_kernel_time": 0.145654, "process_mem_max_rss": "97648640", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m16:11:13.271235 [debug] [MainThread]: Command `dbt build` failed at 16:11:13.271166 after 0.06 seconds
[0m16:11:13.271540 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x102436450>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1068b18d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106481e10>]}
[0m16:11:13.271825 [debug] [MainThread]: Flushing usage events
